sudo: false   # use container-based infrastructure

addons:
  postgresql: "9.4"

services:
  - postgresql

language: python

branches:
  only:
    - master

env:
  global:
    - ROLCA_POSTGRESQL_USER=postgres

# NOTE: Explicit Python versions make Travis job description more informative
matrix:
  include:
    - env: TOX_ENV=py36
      python: "3.6"
    - env: TOX_ENV=py37
      python: "3.7"
    - env: TOX_ENV=py38
      python: "3.8"
    - env: TOX_ENV=docs
      python: "3.6"
    - env: TOX_ENV=linters
      python: "3.6"
    - env: TOX_ENV=packaging
      python: "3.6"

install: pip install tox

script: tox -e $TOX_ENV

after_success:
 - pip install codecov
 - codecov -e TOX_ENV
