# Generated by Django 3.0.2 on 2020-01-03 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_squashed_0007_verbose_names'),
    ]

    operations = [
        migrations.RenameModel(old_name='Photo', new_name='Submission',),
        migrations.AlterModelOptions(
            name='submission',
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
            },
        ),
    ]
