# Generated by Django 3.0.2 on 2020-01-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
    ]
