# Generated by Django 3.0rc1 on 2020-05-23 05:20

from django.db import migrations, models
import rolca.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200515_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=rolca.core.models.generate_file_filename, validators=[rolca.core.models.validate_image]),
        ),
    ]
