# Generated by Django 3.0rc1 on 2020-05-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200523_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Submission'),
        ),
    ]
