# Generated by Django 3.0rc1 on 2020-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200523_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='notice_html',
            field=models.TextField(default=''),
        ),
    ]
