# Generated by Django 3.0rc1 on 2020-07-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('drf_user', '0004_email'),
        ('core', '0009_auto_20200609_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='confirmation_email',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='drf_user.Email',
            ),
        ),
    ]
