# Generated by Django 3.0rc1 on 2020-09-25 18:55
import sys

from django.db import migrations, models
import django.db.models.deletion


def create_submission_sets(apps, schema_editor):
    """Move relation between Submission and File models to later one."""
    Author =  apps.get_model("core", "Author")
    SubmissionSet =  apps.get_model("core", "SubmissionSet")

    for author in Author.objects.all():
        submission_set = SubmissionSet.objects.create()
        submission_set.submissions.add(*author.submission_set.all())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_submissionset_1'),
    ]

    operations = [
        migrations.RunPython(create_submission_sets),
    ]
