# Generated by Django 3.0rc1 on 2020-10-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contest_confirmation_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionset',
            name='author',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author'
            ),
        ),
        migrations.AddField(
            model_name='submissionset',
            name='contest',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submission_sets',
                to='core.Contest',
            ),
        ),
    ]
