# Generated by Django 3.0rc1 on 2020-10-22 19:40

from django.db import migrations


def update_submission_sets(apps, schema_editor):
    """Move relation between Submission and File models to later one."""
    SubmissionSet = apps.get_model("core", "SubmissionSet")

    for submission_set in SubmissionSet.objects.all():
        submission = submission_set.submissions.first()
        if not submission:
            submission_set.delete()
        else:
            submission_set.contest = submission.theme.contest
            submission_set.author = submission.author
            submission_set.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_submissionset_update_1'),
    ]

    operations = [
        migrations.RunPython(update_submission_sets),
    ]
