# Generated by Django 3.0rc1 on 2020-10-25 17:00
import io

from PIL import Image

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import migrations


def enlarge_thumbnails(apps, schema_editor):
    """Enlarge existing thumbnails to the new size."""
    File = apps.get_model("core", "File")

    for file_ in File.objects.all():
        image = Image.open(file_.file)
        image.thumbnail((400, 400), Image.ANTIALIAS)

        thumb = io.BytesIO()
        image.save(thumb, format="jpeg", quality=80, optimize=True, progressive=True)
        file_.thumbnail = InMemoryUploadedFile(
            thumb, None, file_.file.name, 'image/jpeg', thumb.tell(), None
        )

        file_.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_submissionset_update_3'),
    ]

    operations = [
        migrations.RunPython(enlarge_thumbnails),
    ]
