# Generated by Django 3.0rc1 on 2020-10-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_fix_submissionset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(null=True, blank=True),
        ),
    ]
