# Generated by Django 3.0rc1 on 2020-10-02 13:06

from django.db import migrations


def create_payments(apps, schema_editor):
    """Move relation between Submission and File models to later one."""
    Payment = apps.get_model("payment", "Payment")
    SubmissionSet = apps.get_model("core", "SubmissionSet")

    for submission_set in SubmissionSet.objects.all():
        Payment.objects.create(submissionset=submission_set)


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('core', '0012_submissionset_2'),
    ]

    operations = [
        migrations.RunPython(create_payments),
    ]
