# Generated by Django 3.0rc1 on 2020-07-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_contest_confirmation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.File')),
            ],
        ),
    ]
