# Generated by Django 3.0rc1 on 2020-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rating', '0003_authorreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreward',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
