# Generated by Django 3.0rc1 on 2023-04-09 16:02

from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rating', '0004_submissionreward_label'),
    ]

    operations = [
        CryptoExtension(),
    ]
