# Generated by Django 3.0rc1 on 2022-01-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210208_1803'),
        ('rating', '0004_submissionreward_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorreward',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reward',
                to='core.Author',
            ),
        ),
    ]
